name: Build App

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:

  build_android:
    runs-on: ubuntu-24.04
    env:
      # Setup env variables that will be used throughout the workflow
      AAB_NAME: app-release.aab
      AAB_PATH: build/app/outputs/bundle/release
      KEYSTORE_PATH: android/upload-keystore.jks
      KEY_PROPS_PATH: android/key.properties
      SERVICE_ACCOUNT_PATH: store_credentials.json

    steps:
      - name: â¬ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: â• Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'

      - name: ğŸ› ï¸ Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.27.4
          cache: true
          cache-sdk: true

      - name: ğŸ”€  Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1

      - name: ğŸ”¢ Update Version
        run: |
          sed -i "s/version: .*/version: ${{ steps.gitversion.outputs.MajorMinorPatch }}+${{ steps.gitversion.outputs.PreReleaseNumber }}/" pubspec.yaml

      - name: ğŸ“¦ Get dependencies
        run: flutter pub get

      - name: ğŸ”‘ Decode Android keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}" | base64 --decode > ${{ env.KEYSTORE_PATH }}

      - name: ğŸ”‘ Decode Android key properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES_BASE64 }}" | base64 --decode > ${{ env.KEY_PROPS_PATH }}

      - name: ğŸ—ï¸ Generate code dependencies
        run: |
          flutter packages pub run build_runner build

      - name: ğŸ› ï¸ Build release app bundle
        run: flutter build appbundle --release --obfuscate --split-debug-info=./inoventory/logs

      - name: ğŸ”‘ Sign App Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: ğŸ”¼ Upload Signed Bundle To Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-android-release-aab
          path: ${{ env.AAB_PATH }}/${{ env.AAB_NAME }}


#  release:
#    if: github.event_name != 'pull_request'
#    needs: build_android
#    uses: ./.github/workflows/release-app.yml
#    secrets:
#      androidServiceAccountBase64: ${{ secrets.ANDROID_SERVICE_ACCOUNT_BASE64 }}

